services:
  postgres:
    image: docker.io/postgres:12.18
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/data/postgres"
      - "./create-db.sql:/docker-entrypoint-initdb.d/create_database.sql"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/data/postgres

volumes:
  postgres_data:
    driver: local